apiVersion : apps/v1
kind: Deployment
metadata:
  name: aksjuly22 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aksjuly22
  template:
    metadata:
      labels:
        app: aksjuly22 
    spec:
      containers:
        - name: aksjuly22 
          image: azurecontregjuly21.azurecr.io/aksjuly22
          ports:
          - containerPort: 80