apiVersion : apps/v1
kind: Deployment
metadata:
  name: gjuly21new1 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gjuly21new1
  template:
    metadata:
      labels:
        app: gjuly21new1 
    spec:
      containers:
        - name: gjuly21new1 
          image: azurecontregjuly21.azurecr.io/gjuly21new1
          ports:
          - containerPort: 80