apiVersion : apps/v1
kind: Deployment
metadata:
  name: imagedeploykubernetesjuly04 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: imagedeploykubernetesjuly04
  template:
    metadata:
      labels:
        app: imagedeploykubernetesjuly04 
    spec:
      containers:
        - name: imagedeploykubernetesjuly04 
          image: containerregjuly04.azurecr.io/imagedeploykubernetesjuly04
          ports:
          - containerPort: 80