apiVersion : apps/v1
kind: Deployment
metadata:
  name: app1nginxaksjune02 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1nginxaksjune02
  template:
    metadata:
      labels:
        app: app1nginxaksjune02 
    spec:
      containers:
        - name: app1nginxaksjune02 
          image: azurecontregisjuly01.azurecr.io/app1nginxaksjune02
          ports:
          - containerPort: 80